/**
 * Generate compatibility and API reference documentation.
 *
 * Usage:
 *   bun run scripts/generate-docs.ts                 # both (fetches discovery docs live)
 *   bun run scripts/generate-docs.ts --api-only      # route tables only (PR/CI check)
 *   bun run scripts/generate-docs.ts --compatibility-only
 *   bun run scripts/generate-docs.ts --use-cache     # offline: reuse .discovery-cache/
 */

import { join } from 'node:path';
import {
  parseDiscoveryDocument,
  partitionDiscoveryMethods,
  type DiscoveryMethod,
} from './lib/discovery-document.ts';
import { fetchDiscoveryDocument } from './lib/fetch-discovery-document.ts';
import { extractRoutesForAllServices, type ExtractedRoute } from './lib/extract-service-routes.ts';
import { findMatchingRoute } from './lib/path-matching.ts';

const ROOT = join(import.meta.dir, '..');
const REGISTRY_PATH = join(ROOT, 'discovery-document-registry.json');
const METADATA_PATH = join(ROOT, 'docs/service-metadata.json');
const COMPATIBILITY_DIR = join(ROOT, 'docs/compatibility');
const COMPATIBILITY_SERVICES_DIR = join(COMPATIBILITY_DIR, 'services');
const API_REFERENCE_DIR = join(ROOT, 'docs/reference/api');

interface RegistryService {
  readonly name: string;
  readonly displayName: string;
  readonly discoveryUrl: string;
  readonly version: string;
  readonly implementationPath: string;
}

interface RegistryFile {
  readonly services: RegistryService[];
}

interface ServiceMetadata {
  readonly status: 'implemented' | 'experimental' | 'planned';
  readonly dataPlane: string;
  readonly summary: string;
}

interface ServiceMetadataFile {
  readonly services: Record<string, ServiceMetadata>;
}

interface ServiceCoverage {
  readonly registry: RegistryService;
  readonly metadata: ServiceMetadata;
  readonly routes: ExtractedRoute[];
  readonly discoveryAvailable: boolean;
  readonly comparableTotal: number;
  readonly implementedCount: number;
  readonly iamDeferredCount: number;
  readonly implemented: DiscoveryMethod[];
  readonly missing: DiscoveryMethod[];
  readonly iamDeferred: DiscoveryMethod[];
}

const GENERATED_HEADER = '<!-- Generated by scripts/generate-docs.ts. Do not edit by hand. -->\n\n';

async function main(): Promise<void> {
  const apiOnly = process.argv.includes('--api-only');
  const compatibilityOnly = process.argv.includes('--compatibility-only');
  const useCache = process.argv.includes('--use-cache');

  if (apiOnly && compatibilityOnly) {
    throw new Error('Use only one of --api-only or --compatibility-only');
  }

  const generateApi = !compatibilityOnly;
  const generateCompatibility = !apiOnly;

  const registry = JSON.parse(await Bun.file(REGISTRY_PATH).text()) as RegistryFile;
  const metadataFile = JSON.parse(await Bun.file(METADATA_PATH).text()) as ServiceMetadataFile;

  const serviceNames = registry.services.map(service => service.name);
  const routesByService = await extractRoutesForAllServices(serviceNames);

  const coverages: ServiceCoverage[] = [];

  for (const registryService of registry.services) {
    const metadata = metadataFile.services[registryService.name];

    if (!metadata) {
      throw new Error(`Missing docs metadata for service "${registryService.name}"`);
    }

    const routes = routesByService.get(registryService.name) ?? [];

    if (generateCompatibility) {
      coverages.push(await buildServiceCoverage(registryService, metadata, routes, useCache));
    }

    if (generateApi) {
      await writeApiReferencePage(registryService, routes);
    }
  }

  if (generateApi) {
    await writeApiReferenceIndex(registry.services, routesByService);
  }

  if (generateCompatibility) {
    await writeCompatibilityDocs(coverages);
  }

  const parts: string[] = [];

  if (generateApi) {
    parts.push('API reference');
  }

  if (generateCompatibility) {
    parts.push('compatibility matrix');
  }

  console.log(`Generated ${parts.join(' and ')}.`);
}

async function buildServiceCoverage(
  registry: RegistryService,
  metadata: ServiceMetadata,
  routes: ExtractedRoute[],
  useCache: boolean
): Promise<ServiceCoverage> {
  const discoveryJson = await fetchDiscoveryDocument(registry.name, registry.discoveryUrl, {
    useCache,
  });

  if (!discoveryJson) {
    return {
      registry,
      metadata,
      routes,
      discoveryAvailable: false,
      comparableTotal: 0,
      implementedCount: 0,
      iamDeferredCount: 0,
      implemented: [],
      missing: [],
      iamDeferred: [],
    };
  }

  const discovery = parseDiscoveryDocument(discoveryJson);
  const { comparable, iamDeferred } = partitionDiscoveryMethods(discovery.methods);

  const implemented: DiscoveryMethod[] = [];
  const missing: DiscoveryMethod[] = [];

  for (const method of comparable) {
    const match = findMatchingRoute(method.httpMethod, method.path, method.parameters, routes);

    if (match) {
      implemented.push(method);
      continue;
    }

    missing.push(method);
  }

  return {
    registry,
    metadata,
    routes,
    discoveryAvailable: true,
    comparableTotal: comparable.length,
    implementedCount: implemented.length,
    iamDeferredCount: iamDeferred.length,
    implemented,
    missing,
    iamDeferred,
  };
}

async function writeCompatibilityDocs(coverages: readonly ServiceCoverage[]): Promise<void> {
  await ensureDir(COMPATIBILITY_DIR);
  await ensureDir(COMPATIBILITY_SERVICES_DIR);

  await Bun.write(
    join(COMPATIBILITY_DIR, 'index.md'),
    GENERATED_HEADER + renderCompatibilityIndex(coverages)
  );

  for (const coverage of coverages) {
    await Bun.write(
      join(COMPATIBILITY_SERVICES_DIR, `${coverage.registry.name}.md`),
      GENERATED_HEADER + renderServiceCompatibilityPage(coverage)
    );
  }
}

async function writeApiReferenceIndex(
  services: readonly RegistryService[],
  routesByService: Map<string, ExtractedRoute[]>
): Promise<void> {
  await ensureDir(API_REFERENCE_DIR);

  const lines = [
    '# API reference',
    '',
    'HTTP routes registered by kinglet, grouped by emulated GCP service.',
    '',
    '| Service | Routes |',
    '| --- | ---: |',
  ];

  for (const service of services) {
    const routes = routesByService.get(service.name) ?? [];

    lines.push(`| [${service.displayName}](${service.name}.md) | ${routes.length} |`);
  }

  lines.push(
    '',
    'Regenerate with `bun run docs:generate:api`. CI enforces that these files match the codebase.',
    ''
  );

  await Bun.write(join(API_REFERENCE_DIR, 'index.md'), GENERATED_HEADER + lines.join('\n'));
}

async function writeApiReferencePage(
  registry: RegistryService,
  routes: readonly ExtractedRoute[]
): Promise<void> {
  await ensureDir(API_REFERENCE_DIR);

  const lines = [
    `# ${registry.displayName} API`,
    '',
    `**API version:** ${registry.version}`,
    '',
    '| Method | Path | Route ID |',
    '| --- | --- | --- |',
  ];

  for (const route of routes) {
    lines.push(`| \`${route.method}\` | \`${route.path}\` | \`${route.id}\` |`);
  }

  lines.push(
    '',
    'Regenerate with `bun run docs:generate:api`. CI enforces that this file matches the codebase.',
    ''
  );

  await Bun.write(
    join(API_REFERENCE_DIR, `${registry.name}.md`),
    GENERATED_HEADER + lines.join('\n')
  );
}

function renderCompatibilityIndex(coverages: readonly ServiceCoverage[]): string {
  const lines = [
    '# Compatibility matrix',
    '',
    'Endpoint coverage is generated by comparing kinglet routes against the official Google REST discovery document for each service.',
    '',
    '| Service | Status | API version | Endpoint coverage | Data plane | Summary |',
    '| --- | --- | --- | --- | --- | --- |',
  ];

  for (const coverage of coverages) {
    lines.push(
      `| [${coverage.registry.displayName}](services/${coverage.registry.name}.md) | ${formatStatus(coverage.metadata.status)} | ${coverage.registry.version} | ${formatCoverage(coverage)} | ${coverage.metadata.dataPlane} | ${coverage.metadata.summary} |`
    );
  }

  lines.push(
    '',
    '## Status legend',
    '',
    '- **Implemented** — validated against real client libraries and production-style workflows.',
    '- **Experimental** — API surface exists but has not been fully validated; breaking changes may occur.',
    '- **Planned** — not yet implemented.',
    '',
    '## How coverage is calculated',
    '',
    'Coverage counts discovery-document REST methods with a matching kinglet route (same HTTP method and path shape). IAM policy methods (`getIamPolicy`, `setIamPolicy`, `testIamPermissions`) are tracked separately and excluded from the percentage.',
    '',
    'Discovery documents are fetched live from Google when this matrix is regenerated. A scheduled workflow opens PRs to refresh these pages so Google API changes do not appear in unrelated contributor diffs.',
    '',
    'Regenerate locally with `bun run docs:generate:compatibility`.',
    ''
  );

  return lines.join('\n');
}

function renderServiceCompatibilityPage(coverage: ServiceCoverage): string {
  const lines = [
    `# ${coverage.registry.displayName}`,
    '',
    `**Status:** ${formatStatus(coverage.metadata.status)}`,
    `**API version:** ${coverage.registry.version}`,
    `**Data plane:** ${coverage.metadata.dataPlane}`,
    `**Endpoint coverage:** ${formatCoverage(coverage)}`,
    '',
    coverage.metadata.summary,
    '',
  ];

  if (!coverage.discoveryAvailable) {
    lines.push(
      '## Discovery document',
      '',
      'The Google REST discovery document for this service is not publicly fetchable (Memorystore requires credentials). Endpoint coverage against the official API surface is not computed here.',
      '',
      '## Implemented routes in kinglet',
      '',
      renderRouteList(coverage.routes),
      ''
    );

    return lines.join('\n');
  }

  lines.push(
    '## Implemented endpoints',
    '',
    renderDiscoveryMethodList(coverage.implemented),
    '',
    '## Missing endpoints',
    '',
    renderDiscoveryMethodList(coverage.missing),
    '',
    '## IAM endpoints (deferred)',
    '',
    renderDiscoveryMethodList(coverage.iamDeferred),
    '',
    '## API reference',
    '',
    `See [${coverage.registry.displayName} routes](../../reference/api/${coverage.registry.name}.md) for the kinglet route table.`,
    ''
  );

  return lines.join('\n');
}

function renderDiscoveryMethodList(methods: readonly DiscoveryMethod[]): string {
  if (methods.length === 0) {
    return '_None._';
  }

  return methods
    .map(method => `- \`${method.httpMethod}\` \`${method.path}\` — \`${method.id}\``)
    .join('\n');
}

function renderRouteList(routes: readonly ExtractedRoute[]): string {
  if (routes.length === 0) {
    return '_None._';
  }

  return routes
    .map(route => `- \`${route.method}\` \`${route.path}\` — \`${route.id}\``)
    .join('\n');
}

function formatStatus(status: ServiceMetadata['status']): string {
  return status.charAt(0).toUpperCase() + status.slice(1);
}

function formatCoverage(coverage: ServiceCoverage): string {
  if (coverage.metadata.status === 'planned') {
    return 'Not started';
  }

  if (!coverage.discoveryAvailable) {
    return 'Discovery doc unavailable';
  }

  if (coverage.comparableTotal === 0) {
    return '0%';
  }

  const percent = Math.round((coverage.implementedCount / coverage.comparableTotal) * 100);

  return `${coverage.implementedCount}/${coverage.comparableTotal} (${percent}%)`;
}

async function ensureDir(path: string): Promise<void> {
  await Bun.$`mkdir -p ${path}`.quiet();
}

if (import.meta.main) {
  await main();
}
